#!/usr/bin/env bash
################################################################################
# STIG Check: Unknown
# Severity: medium
# Rule Title: Oracle WebLogic must ensure authentication of both client and server during the entire session.
# STIG ID: WBLC-08-000223
# Rule ID: SV-235984r628730_rule
#
# Description:
#     This control focuses on communications protection at the session, versus packet level. 

At the application layer, session IDs are tokens generated by web applications to uniquely identify an application user'\''s session. Web applications utilize session tokens or session IDs in order to establish application user identity. Proper use of session IDs addresses man-in-the-middle attacks, including session hijacking or insertion of false information into a session. 

Application servers must provi
#
# Check Content:
#     1. Access AC
2. From '\''Domain Structure'\'', select '\''Environment'\'' -> '\''Servers'\'' 
3. From the list of servers, select one which needs check for Mutual Authentication configuration verification
4. From '\''Configuration'\'' tab -> '\''General'\'' tab, ensure '\''Listen Port Enabled'\'' checkbox is deselected
5. Ensure '\''SSL Listen Port Enabled'\'' checkbox is selected and a valid port number is in '\''SSL Listen Port'\'' field, e.g., 7002
6. From '\''Configuration'\'' tab -> '\''SSL'\'' tab, click '\''Advanced'\'' link
7. Ensure '\''Two Way Client Cert Behavior'\'' field value is set to '\''Client Certs Requested And Enforced'\''
8. Repeat steps 3-7 for all servers requiring Mutual Authentication configuration checking

If any servers requiring Mutual Authentication do not have the '\''SSL Listen Port Enabled'\'' checkbox selected or the '\''Two Way Client Cert Behavior'\'' field value set to '\''Client Certs Requested And Enforced'\'', this is a finding.
#
# Exit Codes:
#     0 = Check Passed (Compliant)
#     1 = Check Failed (Finding)
#     2 = Check Not Applicable
#     3 = Check Error
################################################################################

# Configuration
VULN_ID="Unknown"
STIG_ID="WBLC-08-000223"
SEVERITY="medium"
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
CONFIG_FILE=""
OUTPUT_JSON=""

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --config)
            CONFIG_FILE="$2"
            shift 2
            ;;
        --output-json)
            OUTPUT_JSON="$2"
            shift 2
            ;;
        -h|--help)
            cat << 'EOF'
Usage: $0 [OPTIONS]

Options:
  --config <file>         Configuration file (JSON)
  --output-json <file>    Output results in JSON format
  -h, --help             Show this help message

Exit Codes:
  0 = Pass (Compliant)
  1 = Fail (Finding)
  2 = Not Applicable
  3 = Error

EOF
            exit 0
            ;;
        *)
            echo "Unknown option: $1"
            exit 3
            ;;
    esac
done

# Load configuration if provided
if [[ -n "$CONFIG_FILE" ]] && [[ -f "$CONFIG_FILE" ]]; then
    # Source configuration or parse JSON as needed
    :
fi

################################################################################
# HELPER FUNCTIONS
################################################################################

# Output results in JSON format
output_json() {
    local status="$1"
    local message="$2"
    local details="$3"

    cat > "$OUTPUT_JSON" << EOF
{
  "vuln_id": "$VULN_ID",
  "stig_id": "$STIG_ID",
  "severity": "$SEVERITY",
  "status": "$status",
  "message": "$message",
  "details": "$details",
  "timestamp": "$TIMESTAMP"
}
EOF
}

################################################################################
# MAIN CHECK LOGIC
################################################################################

main() {
    if ! command -v sqlplus &>/dev/null; then
        echo "ERROR: Oracle client not found"
        [[ -n "$OUTPUT_JSON" ]] && output_json "ERROR" "sqlplus not installed" ""
        exit 3
    fi

    if [[ -z "$ORACLE_USER" ]] || [[ -z "$ORACLE_SID" ]]; then
        echo "ERROR: Oracle credentials not configured"
        [[ -n "$OUTPUT_JSON" ]] && output_json "ERROR" "Credentials missing" ""
        exit 3
    fi

    # Execute SQL query (customize based on specific check)
    output=$(sqlplus -S "$ORACLE_USER"@"$ORACLE_SID" <<EOF
SET PAGESIZE 0 FEEDBACK OFF VERIFY OFF HEADING OFF
-- Add specific query here
EXIT;
EOF
)

    if [[ -n "$output" ]]; then
        echo "PASS: Query executed successfully"
        echo "$output"
        [[ -n "$OUTPUT_JSON" ]] && output_json "PASS" "Query passed" "$output"
        exit 0
    else
        echo "FAIL: No results or query failed"
        [[ -n "$OUTPUT_JSON" ]] && output_json "FAIL" "Query failed" ""
        exit 1
    fi

}

# Run main check
main "$@"
